name: CI Contributor Merger

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - "contributors/*"

concurrency:
  group: ${{ github.ref }}-ci-merger
  cancel-in-progress: true

jobs:
  merger:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.FA_TOKEN }}
    if: ${{ github.event.pull_request.merged == true }}
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: files
        run: |
          echo "CHANGED_FILES=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '[.files[].status]')" >> $GITHUB_ENV

      - name: Post merge comment
        run: |
          if echo "$CHANGED_FILES" | grep -q '"removed"'; then
            gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
              --body "Hey @${{ github.event.pull_request.user.login }}! Thank you for your contribution.
              Even though you decided to remove your contribution, we truly appreciate your effort.
              
              Best Regards,
              @STICKnoLOGIC" \
              --method POST
          else
            gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
              --body "Hi @${{ github.event.pull_request.user.login }}! Your contribution has been merged.
              you can view your contribution here: https://first-accord.js.org?c=${{ github.event.pull_request.user.login }}
              Keep building your skills and check out [these resources](https://github.com/firstcontributions/first-contributions).
              
              Best regards,
              @STICKnoLOGIC" \
              --method POST
          fi


